### ISSUE TITLE
Did you fixed this problem?

### ISSUE THREAD

**Issue by manzoliric** [Suniron/monorepo-nuxt2-nuxt3-problem#1]
Hi, sorry about this Issue!
But i want to know, if you fixed this problem? I really want use nuxt-2 and nuxt-3 in my monorepo project.

**Comment by manzoliric** [comment]
https://github.com/orgs/pnpm/discussions/6104

**Comment by Suniron** [comment]
Hello,

Not really fixed: currently, i can't dev + build my Nuxt Bridge project but I can only dev on my Nuxt 3 app (build is dead).

I just migrated my Nuxt 2 app to Nuxt bridge.
